import { logoHeader, footer, baseStyle, cardStyle, btnStyle, esc } from '../BaseTemplate.js'
import { fmtNaira, fmtDate } from '../../../utils/formatters.js'
const APP_URL = (typeof process !== 'undefined' && (process.env?.CAREFIND_APP_URL || process.env?.APP_URL)) || 'https://carefind.app'

export function customerRegistration({ fullName, email }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">👋</div><h2 style="color:#0f172a;margin:0 0 8px">Welcome to CareFind, ${esc(fullName)}!</h2><p style="color:#888;margin:0">Your account is now active.</p></div><div style="background:#FDFBF7;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px"><p style="margin:0;color:#555;font-size:13px;line-height:1.7">Explore healthcare products, book consultations, and manage orders.</p></div><a href="${APP_URL}/dashboard" style="${btnStyle()}">Go to Dashboard →</a></div>${footer('CareFind','carefind.ng')}</div>`
}

export function orderConfirmation({ fullName, orderRef, items, totalNaira, businessName, deliveryAddress }) {
  const itemRows = (items||[]).map(item=>`<tr><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;color:#334155;font-size:13px">${esc(item.name)}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;color:#334155;font-size:13px;text-align:center">${item.quantity}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;color:#334155;font-size:13px;text-align:right">₦${Number(item.price).toLocaleString('en-NG')}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;color:#334155;font-size:13px;text-align:right">₦${Number(item.price*item.quantity).toLocaleString('en-NG')}</td></tr>`).join('')
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">✅</div><h2 style="color:#0f172a;margin:0 0 8px">Order Confirmed!</h2><p style="color:#888;margin:0">Payment received — thank you for shopping with ${esc(businessName)}.</p></div><div style="background:#f9fafb;border-radius:12px;padding:16px;margin-bottom:24px"><table style="width:100%;border-collapse:collapse"><tr><td style="padding:4px 0;color:#888;font-size:13px;font-weight:600;width:40%">Order Reference</td><td style="padding:4px 0;color:#0f172a;font-size:13px">${esc(orderRef)}</td></tr><tr><td style="padding:4px 0;color:#888;font-size:13px;font-weight:600">Date</td><td style="padding:4px 0;color:#0f172a;font-size:13px">${fmtDate(new Date().toISOString())}</td></tr></table></div><div style="margin-bottom:24px"><h3 style="color:#0f172a;font-size:14px;margin:0 0 12px">Items</h3><table style="width:100%;border-collapse:collapse;border:1px solid #f0f0f0;border-radius:8px;overflow:hidden"><thead><tr style="background:#f9fafb"><th style="padding:10px 12px;text-align:left;color:#64748b;font-size:12px;font-weight:600">Product</th><th style="padding:10px 12px;text-align:center;color:#64748b;font-size:12px;font-weight:600">Qty</th><th style="padding:10px 12px;text-align:right;color:#64748b;font-size:12px;font-weight:600">Price</th><th style="padding:10px 12px;text-align:right;color:#64748b;font-size:12px;font-weight:600">Total</th></tr></thead><tbody>${itemRows}</tbody></table></div><div style="background:#f9fafb;border-radius:12px;padding:16px;margin-bottom:24px"><p style="margin:0;color:#0E6F5A;font-weight:700;font-size:15px">Total Paid: ${fmtNaira(totalNaira)}</p></div>${deliveryAddress?`<div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:16px;margin-bottom:24px"><p style="margin:0 0 4px;color:#166534;font-size:13px;font-weight:600">Delivery Address</p><p style="margin:0;color:#15803d;font-size:13px">${esc(deliveryAddress)}</p></div>`:''}</div>${footer('CareFind','carefind.ng')}</div>`
}

export function subscriptionCreated({ fullName, plan, businessName, expiryDate }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">🎉</div><h2 style="color:#0f172a;margin:0 0 8px">Subscription Active!</h2><p style="color:#888;margin:0">${esc(plan)} plan for ${esc(businessName)}</p></div><div style="background:#FDFBF7;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px"><table style="width:100%;border-collapse:collapse">${[['Plan',plan],['Business',businessName],['Expiry',expiryDate]].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px">${esc(v)}</td></tr>`).join('')}</table></div><a href="${APP_URL}/dashboard" style="${btnStyle()}">Go to Dashboard →</a></div>${footer('CareFind','carefind.ng')}</div>`
}

export function subscriptionExpiry({ fullName, plan, businessName, expiryDate, daysLeft }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">⏰</div><h2 style="color:#0f172a;margin:0 0 8px">Subscription Expiring Soon</h2><p style="color:#888;margin:0">${esc(plan)} for ${esc(businessName)} expires in <strong>${daysLeft} day(s)</strong>.</p></div><div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:12px;padding:20px;margin-bottom:20px"><p style="margin:0;color:#92400e;font-size:13px;font-weight:600">Renew now to avoid service interruption.</p></div><a href="${APP_URL}/billing" style="${btnStyle()}">Renew Subscription →</a></div>${footer('CareFind','carefind.ng')}</div>`
}

export function purchaseConfirmed({ fullName, orderRef, items, totalNaira, businessName, deliveryAddress }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">🛒</div><h2 style="color:#0f172a;margin:0 0 8px">Purchase Confirmed!</h2><p style="color:#888;margin:0">Your order from ${esc(businessName)} is confirmed.</p></div><div style="background:#f9fafb;border-radius:12px;padding:16px;margin-bottom:24px"><p style="margin:0;color:#0E6F5A;font-weight:700;font-size:15px">Total Paid: ${fmtNaira(totalNaira)}</p></div></div>${footer('CareFind','carefind.ng')}</div>`
}

export function passwordReset({ fullName, resetLink }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">🔑</div><h2 style="color:#0f172a;margin:0 0 8px">Reset Your Password</h2><p style="color:#888;margin:0">Hi ${esc(fullName)}, click the button below.</p></div><a href="${resetLink}" style="${btnStyle()}">Reset Password →</a></div>${footer('CareFind','carefind.ng')}</div>`
}

export function emailVerification({ fullName, verifyLink }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">📧</div><h2 style="color:#0f172a;margin:0 0 8px">Verify Your Email</h2><p style="color:#888;margin:0">Hi ${esc(fullName)}, verify your email to activate your account.</p></div><a href="${verifyLink}" style="${btnStyle()}">Verify Email →</a></div>${footer('CareFind','carefind.ng')}</div>`
}

export function appointmentConfirmed({ fullName, businessName, service, date, time, staffName }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">📅</div><h2 style="color:#0f172a;margin:0 0 8px">Appointment Confirmed!</h2><p style="color:#888;margin:0">Hi ${esc(fullName)}, your consultation is booked.</p></div><div style="background:#FDFBF7;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px"><table style="width:100%;border-collapse:collapse">${[['Business',businessName],['Service',service||'Consultation'],['Date',date],['Time',time],['Staff',staffName||'To be assigned']].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px;font-weight:600">${esc(v||'—')}</td></tr>`).join('')}</table></div></div>${footer('CareFind','carefind.ng')}</div>`
}

export function orderStatusUpdate({ fullName, orderRef, status, businessName }) {
  const cfg = { shipped: { icon: '🚚', title: 'Your Order Has Shipped!', c: '#0E6F5A', bg: '#FDFBF7', b: '#e5e7eb' }, delivered: { icon: '📦', title: 'Order Delivered!', c: '#15803d', bg: '#f0fdf4', b: '#bbf7d0' }, cancelled: { icon: '❌', title: 'Order Cancelled', c: '#dc2626', bg: '#fef2f2', b: '#fecaca' }, processing: { icon: '⏳', title: 'Order Processing', c: '#92400e', bg: '#fffbeb', b: '#fcd34d' } }[status] || { icon: '⏳', title: 'Order Update', c: '#92400e', bg: '#fffbeb', b: '#fcd34d' }
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">${cfg.icon}</div><h2 style="color:#0f172a;margin:0 0 8px">${cfg.title}</h2><p style="color:#888;margin:0">Order <strong>${esc(orderRef)}</strong> from ${esc(businessName)}</p></div><div style="background:${cfg.bg};border:1px solid ${cfg.b};border-radius:12px;padding:20px;margin-bottom:20px"><p style="margin:0;color:${cfg.c};font-size:13px;font-weight:600">Status: ${esc((status||'').charAt(0).toUpperCase()+(status||'').slice(1))}</p></div><a href="${APP_URL}/orders/${esc(orderRef)}" style="${btnStyle()}">View Order →</a></div>${footer('CareFind','carefind.ng')}</div>`
}

export function bookingConfirmed({ fullName, businessName, service, date, time }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">🩺</div><h2 style="color:#0f172a;margin:0 0 8px">Booking Confirmed!</h2><p style="color:#888;margin:0">Hi ${esc(fullName)}, your booking with ${esc(businessName)} is confirmed.</p></div><div style="background:#FDFBF7;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px"><table style="width:100%;border-collapse:collapse">${[['Facility',businessName],['Service',service||'Consultation'],['Date',date],['Time',time]].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px;font-weight:600">${esc(v||'—')}</td></tr>`).join('')}</table></div></div>${footer('CareFind','carefind.ng')}</div>`
}

export function bookingCancelled({ fullName, businessName, service, date, time }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Booking Cancelled</h2><p style="color:#888;margin:0 0 16px">Hi ${esc(fullName || 'there')}, your booking has been cancelled.</p><table style="width:100%;border-collapse:collapse">${[['Facility',businessName],['Service',service||'Consultation'],['Date',date],['Time',time]].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px">${esc(v||'—')}</td></tr>`).join('')}</table></div>${footer('CareFind','carefind.app')}</div>`
}

export function consultationBooked({ fullName, professionalName, scheduledAt, service }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Consultation Booked</h2><p style="color:#52525b;font-size:14px">Hi ${esc(fullName || 'there')}, your consultation is booked.</p><p style="color:#52525b;font-size:14px">Professional: <strong>${esc(professionalName || '—')}</strong><br/>Service: ${esc(service || 'Consultation')}<br/>When: ${esc(scheduledAt || '—')}</p></div>${footer('CareFind','carefind.app')}</div>`
}

export function consultationConfirmed({ fullName, professionalName, scheduledAt, service }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Consultation Confirmed</h2><p style="color:#52525b;font-size:14px">Hi ${esc(fullName || 'there')}, your consultation payment is confirmed and your session is booked.</p><p style="color:#52525b;font-size:14px">Professional: <strong>${esc(professionalName || '—')}</strong><br/>Service: ${esc(service || 'Consultation')}<br/>When: ${esc(scheduledAt || '—')}</p></div>${footer('CareFind','carefind.app')}</div>`
}

export function consultationCancelled({ fullName, professionalName, scheduledAt }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Consultation Cancelled</h2><p style="color:#52525b;font-size:14px">Hi ${esc(fullName || 'there')}, your consultation has been cancelled.</p><p style="color:#52525b;font-size:14px">Professional: ${esc(professionalName || '—')}<br/>When: ${esc(scheduledAt || '—')}</p></div>${footer('CareFind','carefind.app')}</div>`
}

export function paymentSuccess({ fullName, amount, reference, purpose }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Payment Successful</h2><p style="color:#52525b;font-size:14px">Hi ${esc(fullName || 'there')}, we received your payment.</p><table style="width:100%;border-collapse:collapse">${[['Amount',amount],['Reference',reference],['Purpose',purpose||'Wallet top-up']].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px">${esc(v||'—')}</td></tr>`).join('')}</table></div>${footer('CareFind','carefind.app')}</div>`
}

export function paymentFailed({ fullName, amount, reference, purpose }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Payment Failed</h2><p style="color:#52525b;font-size:14px">Hi ${esc(fullName || 'there')}, we could not confirm your payment.</p><table style="width:100%;border-collapse:collapse">${[['Amount',amount],['Reference',reference],['Purpose',purpose||'Wallet top-up']].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px">${esc(v||'—')}</td></tr>`).join('')}</table></div>${footer('CareFind','carefind.app')}</div>`
}

export function withdrawalRequested({ fullName, amount, reference, bankName, accountNumber }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Withdrawal Requested</h2><p style="color:#52525b;font-size:14px">Hi ${esc(fullName || 'there')}, your withdrawal request is being processed.</p><table style="width:100%;border-collapse:collapse">${[['Amount',amount],['Reference',reference],['Bank',bankName],['Account',accountNumber]].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px">${esc(v||'—')}</td></tr>`).join('')}</table></div>${footer('CareFind','carefind.app')}</div>`
}

export function withdrawalCompleted({ fullName, amount, reference, bankName, accountNumber }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Withdrawal Settled</h2><p style="color:#52525b;font-size:14px">Hi ${esc(fullName || 'there')}, your withdrawal has been sent to your account.</p><table style="width:100%;border-collapse:collapse">${[['Amount',amount],['Reference',reference],['Bank',bankName],['Account',accountNumber]].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px">${esc(v||'—')}</td></tr>`).join('')}</table></div>${footer('CareFind','carefind.app')}</div>`
}

export function withdrawalFailed({ fullName, amount, reference }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Withdrawal Failed</h2><p style="color:#52525b;font-size:14px">Hi ${esc(fullName || 'there')}, your withdrawal could not be completed. The amount has been returned to your wallet if applicable.</p><p style="color:#52525b;font-size:14px">Reference: <strong>${esc(reference || '—')}</strong><br/>Amount: ${esc(amount || '—')}</p></div>${footer('CareFind','carefind.app')}</div>`
}

export function referralAgentApproved({ agentName, agentEmail, referralCode }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Agent Application Approved</h2><p style="color:#52525b;font-size:14px">Hi ${esc(agentName || 'there')}, your referral agent application has been approved.</p><p style="color:#52525b;font-size:14px">Code: <strong>${esc(referralCode || '—')}</strong><br/>Email: ${esc(agentEmail || '—')}</p></div>${footer('CareFind','carefind.app')}</div>`
}

export function referralAgentRejected({ agentName, reason }) {
  return `<div style="${baseStyle()}">${logoHeader('CareFind')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Application Update</h2><p style="color:#52525b;font-size:14px">Hi ${esc(agentName || 'there')}, we could not approve your referral agent application at this time.</p>${reason ? `<p style="color:#52525b;font-size:14px">Reason: ${esc(reason)}</p>` : ''}</div>${footer('CareFind','carefind.app')}</div>`
}
