// Canonical email event registry. Mirrors the event catalog in
// docs/architecture/Email-System.md §D. Application code references these
// constants instead of raw strings so typos fail at import time, and the
// provider/outbox can restrict sends to known business events.

export const EMAIL_EVENTS = Object.freeze({
  BUSINESS_REGISTERED: 'BUSINESS_REGISTERED',
  BUSINESS_APPROVED: 'BUSINESS_APPROVED',
  BUSINESS_REJECTED: 'BUSINESS_REJECTED',
  STAFF_INVITED: 'STAFF_INVITED',
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  SUBSCRIPTION_STARTED: 'SUBSCRIPTION_STARTED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_EXPIRING: 'SUBSCRIPTION_EXPIRING',
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  WITHDRAWAL_COMPLETED: 'WITHDRAWAL_COMPLETED',
  WITHDRAWAL_FAILED: 'WITHDRAWAL_FAILED',
  REFERRAL_AGENT_APPROVED: 'REFERRAL_AGENT_APPROVED',
  REFERRAL_AGENT_REJECTED: 'REFERRAL_AGENT_REJECTED',

  // CareFind additions
  ACCOUNT_WELCOME: 'ACCOUNT_WELCOME',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  CONSULTATION_BOOKED: 'CONSULTATION_BOOKED',
  CONSULTATION_CONFIRMED: 'CONSULTATION_CONFIRMED',
  CONSULTATION_CANCELLED: 'CONSULTATION_CANCELLED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
})

const EVENT_SET = new Set(Object.values(EMAIL_EVENTS))

export function isKnownEvent(eventType) {
  return EVENT_SET.has(eventType)
}
