export const SAMPLES = {
  registration_owner: { fullName: 'Adebayo Johnson', businessName: 'Lifeline Pharmacy', email: 'adebayo@lifeline.ng' },
  admin_new_registration: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', businessType: 'Pharmacy', state: 'Lagos', email: 'adebayo@lifeline.ng' },
  business_approved: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', ownerEmail: 'adebayo@lifeline.ng' },
  business_rejected: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', reason: 'Incomplete CAC documentation. Please re-upload a valid certificate.' },
  business_suspended: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', reason: 'Policy violation — unverified drug listing.' },
  business_status_update: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', ownerEmail: 'adebayo@lifeline.ng', status: 'active', reason: '' },
  staff_welcome: { fullName: 'Chidera Okoro', role: 'Pharmacist', businessName: 'Lifeline Pharmacy', setupLink: 'https://carefindhub.com/setup?token=demo-token-abc123' },
  subscription_created: { fullName: 'Adebayo Johnson', plan: 'Pro', businessName: 'Lifeline Pharmacy', expiryDate: '2026-09-14' },
  subscription_expiry: { fullName: 'Adebayo Johnson', plan: 'Pro', businessName: 'Lifeline Pharmacy', expiryDate: '2026-09-14', daysLeft: 3 },
  purchase_confirmed: { fullName: 'Adebayo Johnson', orderRef: 'ORD-9F3K2L', businessName: 'Lifeline Pharmacy', totalNaira: 15250, deliveryAddress: '12 Allen Avenue, Ikeja, Lagos', items: [{ name: 'Paracetamol 500mg x20', quantity: 2, price: 1200 }, { name: 'Vitamin C 1000mg', quantity: 1, price: 3500 }, { name: 'ORS Sachets x10', quantity: 3, price: 950 }] },
  customer_registration: { fullName: 'Tunde Bakare', email: 'tunde@carefind.ng' },
  order_confirmation: { fullName: 'Tunde Bakare', orderRef: 'ORD-9F3K2L', businessName: 'MediCare Store', totalNaira: 8750, deliveryAddress: '45 Marina Road, Lagos', items: [{ name: 'Amoxicillin 500mg', quantity: 1, price: 2800 }, { name: 'Ibuprofen 400mg x20', quantity: 2, price: 1500 }] },
  order_status_update: { fullName: 'Tunde Bakare', orderRef: 'ORD-9F3K2L', status: 'shipped', businessName: 'MediCare Store' },
  booking_confirmed: { fullName: 'Tunde Bakare', businessName: 'St. Nicholas Hospital', service: 'General Consultation', date: '2026-04-10', time: '10:30 AM' },
  password_reset: { fullName: 'Adebayo Johnson', resetLink: 'https://carefindhub.com/reset?token=demo-reset-xyz' },
  email_verification: { fullName: 'Adebayo Johnson', verifyLink: 'https://carefindhub.com/verify?token=demo-verify-xyz' },
  appointment_confirmed: { fullName: 'Tunde Bakare', businessName: 'Lagos Health Centre', service: 'General Consultation', date: '2026-04-15', time: '09:00 AM', staffName: 'Dr. Emeka Okafor' },
  credit_reminder: { clientName: 'Ngozi Eze', businessName: 'Lifeline Pharmacy', amount: '₦5,000', dueDate: '15 October 2026' },
  agent_approved: { agentName: 'Kola Adeyemi', agentEmail: 'kola@example.com', referralCode: 'REF-KOLA-21', city: 'Abuja', area: 'Garki' },
  agent_rejected: { agentName: 'Kemi Balogun', reason: 'We could not verify the identity document you uploaded.' },
  booking_cancelled: { fullName: 'Tunde Bakare', businessName: 'St. Nicholas Hospital', service: 'General Consultation', date: '2026-04-10', time: '10:30 AM' },
  consultation_booked: { fullName: 'Tunde Bakare', professionalName: 'Dr. Emeka Okafor', service: 'Video consultation', scheduledAt: '15 April 2026, 9:00 AM' },
  consultation_confirmed: { fullName: 'Tunde Bakare', professionalName: 'Dr. Emeka Okafor', service: 'Video consultation', scheduledAt: '15 April 2026, 9:00 AM' },
  consultation_cancelled: { fullName: 'Tunde Bakare', professionalName: 'Dr. Emeka Okafor', scheduledAt: '15 April 2026, 9:00 AM' },
  payment_success: { fullName: 'Tunde Bakare', amount: '₦10,000', reference: 'CF-TOPUP-8H2K', purpose: 'CareCoin top-up' },
  payment_failed: { fullName: 'Tunde Bakare', amount: '₦10,000', reference: 'CF-TOPUP-8H2K', purpose: 'CareCoin top-up' },
  withdrawal_requested: { fullName: 'Tunde Bakare', businessName: 'Lifeline Pharmacy', amount: '₦45,000', reference: 'WD-7Q2M9', bankName: 'GTBank', accountNumber: '******4821' },
  withdrawal_completed: { fullName: 'Tunde Bakare', businessName: 'Lifeline Pharmacy', amount: '₦45,000', reference: 'WD-7Q2M9', bankName: 'GTBank', accountNumber: '******4821' },
  withdrawal_failed: { fullName: 'Tunde Bakare', businessName: 'Lifeline Pharmacy', amount: '₦45,000', reference: 'WD-7Q2M9' },
  referral_agent_approved: { agentName: 'Kola Adeyemi', agentEmail: 'kola@example.com', referralCode: 'REF-KOLA-21' },
  referral_agent_rejected: { agentName: 'Kemi Balogun', reason: 'We could not verify the identity document you uploaded.' },
}

export const TEMPLATE_META = [
  { key: 'registration_owner', label: 'Customer Registration', app: 'CareHub', icon: '👋', desc: 'Sent when a business registers — under review notice.' },
  { key: 'admin_new_registration', label: 'Admin — New Registration', app: 'CareHub', icon: '🔔', desc: 'Notifies admin a new business is pending approval.' },
  { key: 'business_approved', label: 'Business Approved', app: 'CareHub', icon: '🎉', desc: 'Business account approved — live on CareHub.' },
  { key: 'business_rejected', label: 'Business Rejected', app: 'CareHub', icon: '❌', desc: 'Business registration rejected with reason.' },
  { key: 'business_suspended', label: 'Business Suspended', app: 'CareHub', icon: '⛔', desc: 'Business account suspended.' },
  { key: 'business_status_update', label: 'Business Status Update', app: 'CareHub', icon: '📋', desc: 'Generic status update (active / rejected / suspended / pending).' },
  { key: 'staff_welcome', label: 'Staff Welcome', app: 'CareHub', icon: '👋', desc: 'Invite staff to set up their account via magic link.' },
  { key: 'subscription_created', label: 'Subscription Created', app: 'Both', icon: '🎉', desc: 'Subscription activated / renewed.' },
  { key: 'subscription_expiry', label: 'Subscription Expiring', app: 'Both', icon: '⏰', desc: 'Warning — subscription expires in N days.' },
  { key: 'purchase_confirmed', label: 'Purchase Confirmed', app: 'Both', icon: '✅', desc: 'E-commerce purchase with item table and total.' },
  { key: 'customer_registration', label: 'Customer Registration', app: 'CareFind', icon: '👋', desc: 'CareFind welcome email.' },
  { key: 'order_confirmation', label: 'Order Confirmation', app: 'CareFind', icon: '✅', desc: 'CareFind order with delivery address.' },
  { key: 'order_status_update', label: 'Order Status Update', app: 'Both', icon: '🚚', desc: 'Order shipped / delivered / cancelled / processing.' },
  { key: 'booking_confirmed', label: 'Booking Confirmed', app: 'CareFind', icon: '🩺', desc: 'CareFind service booking confirmed.' },
  { key: 'appointment_confirmed', label: 'Appointment Confirmed', app: 'Both', icon: '📅', desc: 'Appointment booked with date, time, staff.' },
  { key: 'password_reset', label: 'Password Reset', app: 'Both', icon: '🔑', desc: 'Reset link — expires in 15 minutes.' },
  { key: 'email_verification', label: 'Email Verification', app: 'Both', icon: '📧', desc: 'Verify email to activate account.' },
  { key: 'credit_reminder', label: 'Credit Reminder', app: 'CareHub', icon: '💳', desc: 'Reminds a client of an outstanding balance.' },
  { key: 'agent_approved', label: 'Agent Approved', app: 'CareHub', icon: '🤝', desc: 'Referral agent application approved.' },
  { key: 'agent_rejected', label: 'Agent Rejected', app: 'CareHub', icon: '📋', desc: 'Referral agent application declined.' },
  { key: 'booking_cancelled', label: 'Booking Cancelled', app: 'CareFind', icon: '🗓️', desc: 'CareFind booking cancelled.' },
  { key: 'consultation_booked', label: 'Consultation Booked', app: 'CareFind', icon: '🩺', desc: 'Consultation booked with a professional.' },
  { key: 'consultation_confirmed', label: 'Consultation Confirmed', app: 'CareFind', icon: '✅', desc: 'Consultation paid for and confirmed.' },
  { key: 'consultation_cancelled', label: 'Consultation Cancelled', app: 'CareFind', icon: '🗓️', desc: 'Consultation cancelled.' },
  { key: 'payment_success', label: 'Payment Received', app: 'CareFind', icon: '💰', desc: 'Receipt for a payment or top-up.' },
  { key: 'payment_failed', label: 'Payment Failed', app: 'CareFind', icon: '⚠️', desc: 'A payment could not be confirmed.' },
  { key: 'withdrawal_requested', label: 'Withdrawal Requested', app: 'Both', icon: '🏦', desc: 'Withdrawal received and being processed.' },
  { key: 'withdrawal_completed', label: 'Withdrawal Sent', app: 'Both', icon: '🏦', desc: 'Withdrawal sent to the bank.' },
  { key: 'withdrawal_failed', label: 'Withdrawal Failed', app: 'Both', icon: '⚠️', desc: 'Withdrawal could not be completed.' },
  { key: 'referral_agent_approved', label: 'Referral Agent Approved', app: 'CareFind', icon: '🤝', desc: 'CareFind referral agent approved.' },
  { key: 'referral_agent_rejected', label: 'Referral Agent Rejected', app: 'CareFind', icon: '📋', desc: 'CareFind referral agent declined.' },
]
