export const SAMPLES = {
  registration_owner: { fullName: 'Adebayo Johnson', businessName: 'Lifeline Pharmacy', email: 'adebayo@lifeline.ng', password: 'TempPass123!' },
  admin_new_registration: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', businessType: 'Pharmacy', state: 'Lagos', email: 'adebayo@lifeline.ng' },
  business_approved: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', ownerEmail: 'adebayo@lifeline.ng' },
  business_rejected: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', reason: 'Incomplete CAC documentation. Please re-upload a valid certificate.' },
  business_suspended: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', reason: 'Policy violation — unverified drug listing.' },
  business_status_update: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', ownerEmail: 'adebayo@lifeline.ng', status: 'active', reason: '' },
  staff_welcome: { fullName: 'Chidera Okoro', role: 'Pharmacist', businessName: 'Lifeline Pharmacy', setupLink: 'https://carehub.ng/setup?token=demo-token-abc123' },
  subscription_created: { fullName: 'Adebayo Johnson', plan: 'Pro', businessName: 'Lifeline Pharmacy', expiryDate: '2026-09-14' },
  subscription_expiry: { fullName: 'Adebayo Johnson', plan: 'Pro', businessName: 'Lifeline Pharmacy', expiryDate: '2026-09-14', daysLeft: 3 },
  purchase_confirmed: { fullName: 'Adebayo Johnson', orderRef: 'ORD-9F3K2L', businessName: 'Lifeline Pharmacy', totalNaira: 15250, deliveryAddress: '12 Allen Avenue, Ikeja, Lagos', items: [{ name: 'Paracetamol 500mg x20', quantity: 2, price: 1200 }, { name: 'Vitamin C 1000mg', quantity: 1, price: 3500 }, { name: 'ORS Sachets x10', quantity: 3, price: 950 }] },
  customer_registration: { fullName: 'Tunde Bakare', email: 'tunde@carefind.ng' },
  order_confirmation: { fullName: 'Tunde Bakare', orderRef: 'ORD-9F3K2L', businessName: 'MediCare Store', totalNaira: 8750, deliveryAddress: '45 Marina Road, Lagos', items: [{ name: 'Amoxicillin 500mg', quantity: 1, price: 2800 }, { name: 'Ibuprofen 400mg x20', quantity: 2, price: 1500 }] },
  order_status_update: { fullName: 'Tunde Bakare', orderRef: 'ORD-9F3K2L', status: 'shipped', businessName: 'MediCare Store' },
  booking_confirmed: { fullName: 'Tunde Bakare', businessName: 'St. Nicholas Hospital', service: 'General Consultation', date: '2026-04-10', time: '10:30 AM' },
  password_reset: { fullName: 'Adebayo Johnson', resetLink: 'https://carehub.ng/reset?token=demo-reset-xyz' },
  email_verification: { fullName: 'Adebayo Johnson', verifyLink: 'https://carehub.ng/verify?token=demo-verify-xyz' },
  appointment_confirmed: { fullName: 'Tunde Bakare', businessName: 'Lagos Health Centre', service: 'General Consultation', date: '2026-04-15', time: '09:00 AM', staffName: 'Dr. Emeka Okafor' },
}

export const TEMPLATE_META = [
  { key: 'registration_owner', label: 'Customer Registration', app: 'CareHub', icon: '👋', desc: 'Sent when a business registers — under review notice.' },
  { key: 'admin_new_registration', label: 'Admin — New Registration', app: 'CareHub', icon: '🔔', desc: 'Notifies admin a new business is pending approval.' },
  { key: 'business_approved', label: 'Business Approved', app: 'CareHub', icon: '🎉', desc: 'Business account approved — live on CareHub.' },
  { key: 'business_rejected', label: 'Business Rejected', app: 'CareHub', icon: '❌', desc: 'Business registration rejected with reason.' },
  { key: 'business_suspended', label: 'Business Suspended', app: 'CareHub', icon: '⛔', desc: 'Business account suspended.' },
  { key: 'business_status_update', label: 'Business Status Update', app: 'CareHub', icon: '📋', desc: 'Generic status update (active / rejected / suspended / pending).' },
  { key: 'staff_welcome', label: 'Staff Welcome', app: 'CareHub', icon: '👋', desc: 'Invite staff to set up their account via magic link.' },
  { key: 'subscription_created', label: 'Subscription Created', app: 'Both', icon: '🎉', desc: 'Subscription activated / renewed.' },
  { key: 'subscription_expiry', label: 'Subscription Expiring', app: 'Both', icon: '⏰', desc: 'Warning — subscription expires in N days.' },
  { key: 'purchase_confirmed', label: 'Purchase Confirmed', app: 'Both', icon: '✅', desc: 'E-commerce purchase with item table and total.' },
  { key: 'customer_registration', label: 'Customer Registration', app: 'CareFind', icon: '👋', desc: 'CareFind welcome email.' },
  { key: 'order_confirmation', label: 'Order Confirmation', app: 'CareFind', icon: '✅', desc: 'CareFind order with delivery address.' },
  { key: 'order_status_update', label: 'Order Status Update', app: 'Both', icon: '🚚', desc: 'Order shipped / delivered / cancelled / processing.' },
  { key: 'booking_confirmed', label: 'Booking Confirmed', app: 'CareFind', icon: '🩺', desc: 'CareFind service booking confirmed.' },
  { key: 'appointment_confirmed', label: 'Appointment Confirmed', app: 'Both', icon: '📅', desc: 'Appointment booked with date, time, staff.' },
  { key: 'password_reset', label: 'Password Reset', app: 'Both', icon: '🔑', desc: 'Reset link — expires in 15 minutes.' },
  { key: 'email_verification', label: 'Email Verification', app: 'Both', icon: '📧', desc: 'Verify email to activate account.' },
]
