export const SAMPLES = {
  customerRegistration: { fullName: 'Adebayo Johnson', businessName: 'Lifeline Pharmacy', email: 'adebayo@lifeline.ng', password: 'TempPass123!' },
  adminNewRegistration: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', businessType: 'Pharmacy', state: 'Lagos', email: 'adebayo@lifeline.ng' },
  businessApproved: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', ownerEmail: 'adebayo@lifeline.ng' },
  businessRejected: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', reason: 'Incomplete CAC documentation. Please re-upload a valid certificate.' },
  businessSuspended: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', reason: 'Policy violation — unverified drug listing.' },
  businessStatusUpdate: { businessName: 'Lifeline Pharmacy', ownerName: 'Adebayo Johnson', ownerEmail: 'adebayo@lifeline.ng', status: 'active', reason: '' },
  staffWelcome: { fullName: 'Chidera Okoro', role: 'Pharmacist', businessName: 'Lifeline Pharmacy', setupLink: 'https://carehub.ng/setup?token=demo-token-abc123' },
  subscriptionCreated: { fullName: 'Adebayo Johnson', plan: 'Pro', businessName: 'Lifeline Pharmacy', expiryDate: '2026-09-14' },
  subscriptionExpiry: { fullName: 'Adebayo Johnson', plan: 'Pro', businessName: 'Lifeline Pharmacy', expiryDate: '2026-09-14', daysLeft: 3 },
  purchaseConfirmed: { fullName: 'Adebayo Johnson', orderRef: 'ORD-9F3K2L', businessName: 'Lifeline Pharmacy', totalNaira: 15250, deliveryAddress: '12 Allen Avenue, Ikeja, Lagos', items: [{ name: 'Paracetamol 500mg x20', quantity: 2, price: 1200 }, { name: 'Vitamin C 1000mg', quantity: 1, price: 3500 }, { name: 'ORS Sachets x10', quantity: 3, price: 950 }] },
  orderConfirmation: { fullName: 'Tunde Bakare', orderRef: 'ORD-9F3K2L', businessName: 'MediCare Store', totalNaira: 8750, deliveryAddress: '45 Marina Road, Lagos', items: [{ name: 'Amoxicillin 500mg', quantity: 1, price: 2800 }, { name: 'Ibuprofen 400mg x20', quantity: 2, price: 1500 }] },
  orderStatusUpdate: { fullName: 'Tunde Bakare', orderRef: 'ORD-9F3K2L', status: 'shipped', businessName: 'MediCare Store' },
  bookingConfirmed: { fullName: 'Tunde Bakare', businessName: 'St. Nicholas Hospital', service: 'General Consultation', date: '2026-04-10', time: '10:30 AM' },
  passwordReset: { fullName: 'Adebayo Johnson', resetLink: 'https://carehub.ng/reset?token=demo-reset-xyz' },
  emailVerification: { fullName: 'Adebayo Johnson', verifyLink: 'https://carehub.ng/verify?token=demo-verify-xyz' },
  appointmentConfirmed: { fullName: 'Tunde Bakare', businessName: 'Lagos Health Centre', service: 'General Consultation', date: '2026-04-15', time: '09:00 AM', staffName: 'Dr. Emeka Okafor' },
}

export const TEMPLATE_META = [
  { key: 'customerRegistration', label: 'Customer Registration', app: 'CareHub', icon: '👋', desc: 'Sent when a business registers — under review notice.' },
  { key: 'adminNewRegistration', label: 'Admin — New Registration', app: 'CareHub', icon: '🔔', desc: 'Notifies admin a new business is pending approval.' },
  { key: 'businessApproved', label: 'Business Approved', app: 'CareHub', icon: '🎉', desc: 'Business account approved — live on CareHub.' },
  { key: 'businessRejected', label: 'Business Rejected', app: 'CareHub', icon: '❌', desc: 'Business registration rejected with reason.' },
  { key: 'businessSuspended', label: 'Business Suspended', app: 'CareHub', icon: '⛔', desc: 'Business account suspended.' },
  { key: 'businessStatusUpdate', label: 'Business Status Update', app: 'CareHub', icon: '📋', desc: 'Generic status update (active / rejected / suspended / pending).' },
  { key: 'staffWelcome', label: 'Staff Welcome', app: 'CareHub', icon: '👋', desc: 'Invite staff to set up their account via magic link.' },
  { key: 'subscriptionCreated', label: 'Subscription Created', app: 'Both', icon: '🎉', desc: 'Subscription activated / renewed.' },
  { key: 'subscriptionExpiry', label: 'Subscription Expiring', app: 'Both', icon: '⏰', desc: 'Warning — subscription expires in N days.' },
  { key: 'purchaseConfirmed', label: 'Purchase Confirmed', app: 'Both', icon: '✅', desc: 'E-commerce purchase with item table and total.' },
  { key: 'orderConfirmation', label: 'Order Confirmation', app: 'CareFind', icon: '✅', desc: 'CareFind order with delivery address.' },
  { key: 'orderStatusUpdate', label: 'Order Status Update', app: 'Both', icon: '🚚', desc: 'Order shipped / delivered / cancelled / processing.' },
  { key: 'bookingConfirmed', label: 'Booking Confirmed', app: 'CareFind', icon: '🩺', desc: 'CareFind service booking confirmed.' },
  { key: 'appointmentConfirmed', label: 'Appointment Confirmed', app: 'Both', icon: '📅', desc: 'Appointment booked with date, time, staff.' },
  { key: 'passwordReset', label: 'Password Reset', app: 'Both', icon: '🔑', desc: 'Reset link — expires in 15 minutes.' },
  { key: 'emailVerification', label: 'Email Verification', app: 'Both', icon: '📧', desc: 'Verify email to activate account.' },
]
