import { logoHeader, footer, baseStyle, cardStyle, btnStyle, esc } from './BaseTemplate.js'
const APP_URL = typeof process !== 'undefined' && process.env?.APP_URL ? process.env.APP_URL : 'https://carefindhub.com'

export function customerRegistration({ fullName, businessName, email, password }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">👋</div><h2 style="color:#0f172a;margin:0 0 8px">Welcome to CareHub, ${esc(fullName)}!</h2><p style="color:#888;margin:0">Your business <strong>${esc(businessName)}</strong> is now on CareHub.</p></div><div style="background:#FDFBF7;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px"><p style="margin:0;color:#555;font-size:13px;line-height:1.7">Your account is <strong>under review</strong> by the CareHub admin team. You will receive an email within <strong>24 hours</strong> once approved.</p></div><div style="background:#f9fafb;border-radius:12px;padding:16px;margin-bottom:20px"><p style="margin:0;color:#888;font-size:12px;line-height:1.6">Email: ${esc(email)}</p></div><a href="${APP_URL}/login" style="${btnStyle()}">Go to Sign In →</a></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function subscriptionCreated({ fullName, plan, businessName, expiryDate }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">🎉</div><h2 style="color:#0f172a;margin:0 0 8px">Subscription Active!</h2><p style="color:#888;margin:0">${esc(plan)} plan for ${esc(businessName)}</p></div><div style="background:#FDFBF7;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px"><table style="width:100%;border-collapse:collapse">${[['Plan',plan],['Business',businessName],['Expiry',expiryDate]].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px">${esc(v)}</td></tr>`).join('')}</table></div><a href="${APP_URL}/dashboard" style="${btnStyle()}">Go to Dashboard →</a></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function subscriptionExpiry({ fullName, plan, businessName, expiryDate, daysLeft }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">⏰</div><h2 style="color:#0f172a;margin:0 0 8px">Subscription Expiring Soon</h2><p style="color:#888;margin:0">${esc(plan)} for ${esc(businessName)} expires in <strong>${daysLeft} day(s)</strong>.</p></div><div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:12px;padding:20px;margin-bottom:20px"><p style="margin:0;color:#92400e;font-size:13px;font-weight:600">Renew now to avoid service interruption.</p></div><a href="${APP_URL}/billing" style="${btnStyle()}">Renew Subscription →</a></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function purchaseConfirmed({ fullName, orderRef, items, totalNaira, businessName, deliveryAddress }) {
  const itemRows = (items||[]).map(item=>`<tr><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;color:#334155;font-size:13px">${esc(item.name)}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;color:#334155;font-size:13px;text-align:center">${item.quantity}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;color:#334155;font-size:13px;text-align:right">₦${Number(item.price).toLocaleString('en-NG')}</td><td style="padding:10px 12px;border-bottom:1px solid #f0f0f0;color:#334155;font-size:13px;text-align:right">₦${Number(item.price*item.quantity).toLocaleString('en-NG')}</td></tr>`).join('')
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">✅</div><h2 style="color:#0f172a;margin:0 0 8px">Purchase Confirmed!</h2><p style="color:#888;margin:0">Thank you for shopping with ${esc(businessName)}, ${esc(fullName)}.</p></div><div style="background:#f9fafb;border-radius:12px;padding:16px;margin-bottom:24px"><table style="width:100%;border-collapse:collapse"><tr><td style="padding:4px 0;color:#888;font-size:13px;font-weight:600;width:40%">Order Reference</td><td style="padding:4px 0;color:#0f172a;font-size:13px">${esc(orderRef)}</td></tr></table></div><div style="margin-bottom:24px"><h3 style="color:#0f172a;font-size:14px;margin:0 0 12px">Items</h3><table style="width:100%;border-collapse:collapse;border:1px solid #f0f0f0;border-radius:8px;overflow:hidden"><thead><tr style="background:#f9fafb"><th style="padding:10px 12px;text-align:left;color:#64748b;font-size:12px;font-weight:600">Product</th><th style="padding:10px 12px;text-align:center;color:#64748b;font-size:12px;font-weight:600">Qty</th><th style="padding:10px 12px;text-align:right;color:#64748b;font-size:12px;font-weight:600">Price</th><th style="padding:10px 12px;text-align:right;color:#64748b;font-size:12px;font-weight:600">Total</th></tr></thead><tbody>${itemRows}</tbody></table></div><div style="background:#f9fafb;border-radius:12px;padding:16px;margin-bottom:24px"><p style="margin:0;color:#0E6F5A;font-weight:700;font-size:15px">Total: ₦${Number(totalNaira).toLocaleString('en-NG')}</p></div>${deliveryAddress?`<div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:16px;margin-bottom:24px"><p style="margin:0 0 4px;color:#166534;font-size:13px;font-weight:600">Delivery Address</p><p style="margin:0;color:#15803d;font-size:13px">${esc(deliveryAddress)}</p></div>`:''}</div>${footer('CareHub','carefindhub.com')}</div>`
}

export function passwordReset({ fullName, resetLink }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">🔑</div><h2 style="color:#0f172a;margin:0 0 8px">Reset Your Password</h2><p style="color:#888;margin:0">Hi ${esc(fullName)}, click the button below to set a new password.</p></div><a href="${resetLink}" style="${btnStyle()}">Reset Password →</a><p style="margin-top:16px;font-size:12px;color:#aaa;text-align:center">This link expires in 15 minutes.</p></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function emailVerification({ fullName, verifyLink }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">📧</div><h2 style="color:#0f172a;margin:0 0 8px">Verify Your Email</h2><p style="color:#888;margin:0">Hi ${esc(fullName)}, click the button below to verify your email address.</p></div><a href="${verifyLink}" style="${btnStyle()}">Verify Email →</a></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function appointmentConfirmed({ fullName, businessName, service, date, time, staffName }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">📅</div><h2 style="color:#0f172a;margin:0 0 8px">Appointment Confirmed!</h2><p style="color:#888;margin:0">Hi ${esc(fullName)}, your appointment has been booked.</p></div><div style="background:#FDFBF7;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px"><table style="width:100%;border-collapse:collapse">${[['Business',businessName],['Service',service||'Consultation'],['Date',date],['Time',time],['Staff',staffName||'To be assigned']].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px;font-weight:600">${esc(v||'—')}</td></tr>`).join('')}</table></div></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function businessApproved({ businessName, ownerName, ownerEmail }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:56px;margin-bottom:12px">🎉</div><h2 style="color:#0f172a;margin:0 0 8px">Your Account is Approved!</h2><p style="color:#888;margin:0">Welcome to CareHub, ${esc(ownerName)}!</p></div><div style="background:#FDFBF7;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px"><p style="margin:0 0 8px;color:#0E6F5A;font-weight:700;font-size:14px">✅ ${esc(businessName)} is now live on CareHub!</p><p style="margin:0;color:#555;font-size:13px;line-height:1.7">Your account has been approved. You can now log in and start using all features including POS, Inventory, Client Management, and CareFind listing.</p></div><div style="background:#f9fafb;border-radius:12px;padding:20px;margin-bottom:20px"><p style="margin:0 0 12px;font-weight:700;color:#0f172a;font-size:14px">Your Login Details:</p><p style="margin:0 0 6px;font-size:13px;color:#555"><strong>Website:</strong> ${APP_URL}</p><p style="margin:0 0 6px;font-size:13px;color:#555"><strong>Email:</strong> ${esc(ownerEmail)}</p><p style="margin:0;font-size:13px;color:#555"><strong>Password:</strong> The password you set during registration</p></div><a href="${APP_URL}/login" style="${btnStyle()}">Log In to Your Dashboard →</a><p style="margin-top:20px;font-size:12px;color:#aaa;text-align:center">Need help? Reply to this email or contact support@mail.carefindhub.com</p></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function businessRejected({ businessName, ownerName, reason }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Application Update</h2><p style="color:#888;margin:0 0 24px">Dear ${esc(ownerName)},</p><p style="color:#555;font-size:14px;line-height:1.7;margin-bottom:20px">Thank you for registering <strong>${esc(businessName)}</strong> on CareHub. After reviewing your application, we were unable to approve your account at this time.</p>${reason ? `<div style="background:#fef2f2;border:1px solid #fecaca;border-radius:10px;padding:14px;margin-bottom:20px"><p style="margin:0;color:#dc2626;font-size:13px"><strong>Reason:</strong> ${esc(reason)}</p></div>` : ''}<p style="color:#555;font-size:13px;line-height:1.7">If you believe this is an error or would like to reapply, please contact our support team at <strong>support@mail.carefindhub.com</strong></p><a href="mailto:support@mail.carefindhub.com" style="${btnStyle()}">Contact Support</a></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function businessSuspended({ businessName, ownerName, reason }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Account Suspended</h2><p style="color:#888;margin:0 0 24px">Dear ${esc(ownerName)},</p><p style="color:#555;font-size:14px;line-height:1.7;margin-bottom:20px">Your business <strong>${esc(businessName)}</strong> has been suspended.${reason ? ` <strong>Reason:</strong> ${esc(reason)}` : ''}</p><p style="color:#555;font-size:13px;line-height:1.7">Please contact support@mail.carefindhub.com if you have questions.</p></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function businessStatusUpdate({ businessName, ownerName, ownerEmail, status, reason }) {
  if (status === 'active') return businessApproved({ businessName, ownerName, ownerEmail })
  if (status === 'rejected') return businessRejected({ businessName, ownerName, reason })
  if (status === 'suspended') return businessSuspended({ businessName, ownerName, reason })
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">Application Update — Action Required</h2><p style="color:#888;margin:0 0 24px">Dear ${esc(ownerName)},</p><p style="color:#555;font-size:14px;line-height:1.7;margin-bottom:20px">Your application for <strong>${esc(businessName)}</strong> requires attention.${reason ? ` <strong>Details:</strong> ${esc(reason)}` : ''}</p><p style="color:#555;font-size:13px;line-height:1.7">Please log in or contact support@mail.carefindhub.com for next steps.</p><a href="${APP_URL}/login" style="${btnStyle()}">Go to CareHub →</a></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function adminNewRegistration({ businessName, ownerName, businessType, state, email }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><h2 style="color:#0f172a;margin:0 0 8px">🔔 New Business Registration</h2><p style="color:#888;margin:0 0 24px">A new business has registered and is waiting for your approval.</p><div style="background:#f9fafb;border-radius:12px;padding:20px;margin-bottom:20px"><table style="width:100%;border-collapse:collapse">${[['Business Name',businessName],['Owner',ownerName],['Business Type',businessType],['State',state],['Email',email]].map(([l,v])=>`<tr><td style="padding:8px 0;color:#888;font-weight:600;font-size:13px;width:40%">${l}</td><td style="padding:8px 0;color:#0f172a;font-size:13px">${esc(v)||'—'}</td></tr>`).join('')}</table></div><div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:10px;padding:14px;margin-bottom:20px"><p style="margin:0;color:#92400e;font-size:13px;font-weight:600">⏳ This business is pending your approval. Log in to the admin panel to review and approve.</p></div><a href="${APP_URL}/login" style="${btnStyle()}">Go to Admin Panel →</a></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function staffWelcome({ fullName, role, businessName, setupLink }) {
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">👋</div><h2 style="color:#0f172a;margin:0 0 8px">You're Invited to Join ${esc(businessName)}!</h2><p style="color:#888;margin:0">Hi ${esc(fullName)}, you've been added as <strong>${esc(role)}</strong> on CareHub.</p></div><div style="background:#FDFBF7;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px"><p style="margin:0;color:#555;font-size:13px;line-height:1.7">Click the button below to set up your account and get started. This invitation expires in <strong>48 hours</strong>.</p></div><a href="${setupLink}" style="${btnStyle()}">Set Up Your Account →</a><p style="margin-top:16px;font-size:12px;color:#aaa;text-align:center">Didn't expect this? You can safely ignore this email.</p></div>${footer('CareHub','carefindhub.com')}</div>`
}

export function orderStatusUpdate({ fullName, orderRef, status, businessName }) {
  const statusConfig = { shipped: { icon: '🚚', title: 'Your Order Has Shipped!', color: '#0E6F5A', bg: '#FDFBF7', border: '#e5e7eb' }, delivered: { icon: '📦', title: 'Order Delivered!', color: '#15803d', bg: '#f0fdf4', border: '#bbf7d0' }, cancelled: { icon: '❌', title: 'Order Cancelled', color: '#dc2626', bg: '#fef2f2', border: '#fecaca' }, processing: { icon: '⏳', title: 'Order Processing', color: '#92400e', bg: '#fffbeb', border: '#fcd34d' } }
  const cfg = statusConfig[status] || statusConfig.processing
  return `<div style="${baseStyle()}">${logoHeader('CareHub')}<div style="${cardStyle()}"><div style="text-align:center;margin-bottom:24px"><div style="font-size:48px;margin-bottom:12px">${cfg.icon}</div><h2 style="color:#0f172a;margin:0 0 8px">${cfg.title}</h2><p style="color:#888;margin:0">Order <strong>${esc(orderRef)}</strong> from ${esc(businessName)}</p></div><div style="background:${cfg.bg};border:1px solid ${cfg.border};border-radius:12px;padding:20px;margin-bottom:20px"><p style="margin:0;color:${cfg.color};font-size:13px;font-weight:600">Status: ${esc(status.charAt(0).toUpperCase()+status.slice(1))}</p></div><a href="${APP_URL}/orders/${esc(orderRef)}" style="${btnStyle()}">View Order →</a></div>${footer('CareHub','carefindhub.com')}</div>`
}
